## **Introduction**

- **Dataset is a collection of audio features including acoustic attributes such as tempo, MFCCs, spectral characteristics, and more**
- **Use the dataaset under 'train.csv' to build a classification model and correctly classify audio files into genres**
- **Test on the 'test.csv' file and submit a file called 'submission.csv' with the corresponding classifications**

## **Importing Datasets, Libraries and EDA**

In [113]:
train = pd.read_csv('/Users/nischalkashyap/Desktop/PESU/Semester_5/MI/Hackathon/train.csv')
test = pd.read_csv("/Users/nischalkashyap/Desktop/PESU/Semester_5/MI/Hackathon/test.csv")

In [114]:
train

,filename,length,chroma_stft_mean,chroma_stft_var,rms_mean,rms_var,spectral_centroid_mean,spectral_centroid_var,spectral_bandwidth_mean,spectral_bandwidth_var,...,mfcc16_var,mfcc17_mean,mfcc17_var,mfcc18_mean,mfcc18_var,mfcc19_mean,mfcc19_var,mfcc20_mean,mfcc20_var,label
0,pop.00072.5.wav,66149,0.464264,0.079744,0.228116,0.007791,2156.231325,3.334553e+05,2295.327890,301528.295866,...,36.512493,0.587634,44.336262,3.168914,31.690376,0.719836,50.416603,-3.192938,25.115688,pop
1,jazz.00038.9.wav,66149,0.254604,0.090115,0.075960,0.002236,1439.715643,6.895570e+04,1532.279764,78968.523547,...,29.887444,-0.706779,105.123726,2.879812,157.346725,3.201282,71.674042,-1.664307,53.640949,jazz
2,disco.00055.3.wav,66149,0.488070,0.065943,0.119709,0.001558,2049.831819,1.320308e+05,2043.472368,71699.726714,...,29.158789,-4.570374,24.995367,-0.735507,33.519482,-2.301054,38.444759,6.482006,50.393089,disco
3,rock.00025.9.wav,66149,0.440747,0.071972,0.108535,0.001491,2237.056815,1.298620e+05,2070.706749,62747.206984,...,33.833458,-5.574619,29.497013,3.903063,18.930311,-2.205716,26.832264,0.551784,25.199505,rock
4,jazz.00013.4.wav,66149,0.369718,0.090648,0.052010,0.000124,1775.591113,6.664517e+04,2351.155395,51753.800714,...,48.042686,-3.686353,47.710155,3.593751,70.004326,0.011506,85.980957,1.892704,108.339722,jazz
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8986,hiphop.00065.4.wav,66149,0.462670,0.095231,0.193568,0.019747,2347.298046,1.844716e+06,2726.496978,230626.501970,...,30.122299,-0.610546,35.591270,-2.011291,41.289818,-2.381295,26.049856,-6.093438,23.417213,hiphop
8987,classical.00065.4.wav,66149,0.173276,0.085205,0.024984,0.000277,845.785117,1.655318e+04,1396.738918,95543.330422,...,39.011562,-12.885547,20.443741,-6.172429,30.038237,-3.897101,64.039413,-8.887048,40.697903,classical
8988,country.00044.3.wav,66149,0.291293,0.088386,0.149195,0.001361,2579.336949,6.288279e+05,2714.346339,110427.695082,...,74.335464,-10.504237,106.257889,-5.624926,37.167961,5.237616,29.307474,-6.440866,70.347389,country
8989,blues.00013.3.wav,66149,0.249859,0.089284,0.130065,0.003803,1230.642086,1.891168e+05,1800.824216,65413.553514,...,39.797985,-9.799487,42.763683,-6.866515,57.569805,-5.379220,70.344284,-7.938619,81.895149,blues
8990,country.00048.9.wav,66149,0.332883,0.092598,0.100225,0.001413,1586.161823,7.114829e+05,2219.256156,228161.688458,...,50.437626,-6.376563,34.499088,-3.707427,41.206928,-6.056847,87.959717,-7.277541,36.711807,country

In [115]:
train.shape

(8991, 60)

In [116]:
train.info

<bound method DataFrame.info of                    filename  length  chroma_stft_mean  chroma_stft_var  \
0           pop.00072.5.wav   66149          0.464264         0.079744
1          jazz.00038.9.wav   66149          0.254604         0.090115
2         disco.00055.3.wav   66149          0.488070         0.065943
3          rock.00025.9.wav   66149          0.440747         0.071972
4          jazz.00013.4.wav   66149          0.369718         0.090648
...                     ...     ...               ...              ...
8986     hiphop.00065.4.wav   66149          0.462670         0.095231
8987  classical.00065.4.wav   66149          0.173276         0.085205
8988    country.00044.3.wav   66149          0.291293         0.088386
8989      blues.00013.3.wav   66149          0.249859         0.089284
8990    country.00048.9.wav   66149          0.332883         0.092598

      rms_mean   rms_var  spectral_centroid_mean  spectral_centroid_var  \
0     0.228116  0.007791             2156.231325           3.334553e+05
1     0.075960  0.002236             1439.715643           6.895570e+04
2     0.119709  0.001558             2049.831819           1.320308e+05
3     0.108535  0.001491             2237.056815           1.298620e+05
4     0.052010  0.000124             1775.591113           6.664517e+04
...        ...       ...                     ...                    ...
8986  0.193568  0.019747             2347.298046           1.844716e+06
8987  0.024984  0.000277              845.785117           1.655318e+04
8988  0.149195  0.001361             2579.336949           6.288279e+05
8989  0.130065  0.003803             1230.642086           1.891168e+05
8990  0.100225  0.001413             1586.161823           7.114829e+05

      spectral_bandwidth_mean  spectral_bandwidth_var  ...  mfcc16_var  \
0                 2295.327890           301528.295866  ...   36.512493
1                 1532.279764            78968.523547  ...   29.887444
2                 2043.472368            71699.726714  ...   29.158789
3                 2070.706749            62747.206984  ...   33.833458
4                 2351.155395            51753.800714  ...   48.042686
...                       ...                     ...  ...         ...
8986              2726.496978           230626.501970  ...   30.122299
8987              1396.738918            95543.330422  ...   39.011562
8988              2714.346339           110427.695082  ...   74.335464
8989              1800.824216            65413.553514  ...   39.797985
8990              2219.256156           228161.688458  ...   50.437626

      mfcc17_mean  mfcc17_var  mfcc18_mean  mfcc18_var  mfcc19_mean  \
0        0.587634   44.336262     3.168914   31.690376     0.719836
1       -0.706779  105.123726     2.879812  157.346725     3.201282
2       -4.570374   24.995367    -0.735507   33.519482    -2.301054
3       -5.574619   29.497013     3.903063   18.930311    -2.205716
4       -3.686353   47.710155     3.593751   70.004326     0.011506
...           ...         ...          ...         ...          ...
8986    -0.610546   35.591270    -2.011291   41.289818    -2.381295
8987   -12.885547   20.443741    -6.172429   30.038237    -3.897101
8988   -10.504237  106.257889    -5.624926   37.167961     5.237616
8989    -9.799487   42.763683    -6.866515   57.569805    -5.379220
8990    -6.376563   34.499088    -3.707427   41.206928    -6.056847

      mfcc19_var  mfcc20_mean  mfcc20_var      label
0      50.416603    -3.192938   25.115688        pop
1      71.674042    -1.664307   53.640949       jazz
2      38.444759     6.482006   50.393089      disco
3      26.832264     0.551784   25.199505       rock
4      85.980957     1.892704  108.339722       jazz
...          ...          ...         ...        ...
8986   26.049856    -6.093438   23.417213     hiphop
8987   64.039413    -8.887048   40.697903  classical
8988   29.307474    -6.440866   70.347389    country
8989   70.344284    -7.938619   81.895149      blues
8990   87.959717    -7.277541   36.711807    country

[8991 rows x 60 columns]>

In [117]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelBinarizer
from tensorflow import keras
from tensorflow.keras import layers

## **Building the Sequential Model using Keras**

In [118]:
# Split dataset and encode using one hot encoding
X = train.drop(columns=['filename','label'], axis = 1)
y = train['label']
label_binarizer = LabelBinarizer()
y = label_binarizer.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardise train data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = keras.Sequential()

# Input layer has 58 features 
model.add(layers.Dense(58, activation='relu'))
# Hidden layer
model.add(layers.Dense(48, activation='relu'))
# Output layer has 10 genres
output_categories = 10
model.add(layers.Dense(output_categories, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs= 20, batch_size= 16, validation_data=(X_test, y_test))
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Loss: {loss}, Test Accuracy: {accuracy}")

Epoch 1/20
450/450 [==============================] - 1s 901us/step - loss: 1.3493 - accuracy: 0.5257 - val_loss: 1.0583 - val_accuracy: 0.6337
Epoch 2/20
450/450 [==============================] - 0s 763us/step - loss: 0.8746 - accuracy: 0.7005 - val_loss: 0.8946 - val_accuracy: 0.6898
Epoch 3/20
450/450 [==============================] - 0s 803us/step - loss: 0.7337 - accuracy: 0.7501 - val_loss: 0.7657 - val_accuracy: 0.7565
Epoch 4/20
450/450 [==============================] - 0s 1ms/step - loss: 0.6417 - accuracy: 0.7839 - val_loss: 0.7192 - val_accuracy: 0.7660
Epoch 5/20
450/450 [==============================] - 0s 851us/step - loss: 0.5796 - accuracy: 0.7998 - val_loss: 0.6843 - val_accuracy: 0.7727
Epoch 6/20
450/450 [==============================] - 0s 859us/step - loss: 0.5245 - accuracy: 0.8174 - val_loss: 0.6459 - val_accuracy: 0.7916
Epoch 7/20
450/450 [==============================] - 0s 787us/step - loss: 0.4812 - accuracy: 0.8354 - val_loss: 0.6144 - val_accuracy: 0.7971
Epoch 8/20
450/450 [==============================] - 0s 773us/step - loss: 0.4380 - accuracy: 0.8529 - val_loss: 0.5998 - val_accuracy: 0.7999
Epoch 9/20
450/450 [==============================] - 0s 764us/step - loss: 0.4044 - accuracy: 0.8660 - val_loss: 0.5824 - val_accuracy: 0.8171
Epoch 10/20
450/450 [==============================] - 0s 778us/step - loss: 0.3787 - accuracy: 0.8731 - val_loss: 0.5993 - val_accuracy: 0.8127
Epoch 11/20
450/450 [==============================] - 0s 777us/step - loss: 0.3495 - accuracy: 0.8864 - val_loss: 0.6014 - val_accuracy: 0.8132
Epoch 12/20
450/450 [==============================] - 0s 760us/step - loss: 0.3282 - accuracy: 0.8899 - val_loss: 0.5784 - val_accuracy: 0.8249
Epoch 13/20
450/450 [==============================] - 0s 760us/step - loss: 0.3021 - accuracy: 0.9027 - val_loss: 0.5527 - val_accuracy: 0.8338
Epoch 14/20
450/450 [==============================] - 0s 758us/step - loss: 0.2845 - accuracy: 0.9080 - val_loss: 0.5813 - val_accuracy: 0.8271
Epoch 15/20
450/450 [==============================] - 0s 755us/step - loss: 0.2647 - accuracy: 0.9155 - val_loss: 0.5627 - val_accuracy: 0.8371
Epoch 16/20
450/450 [==============================] - 0s 829us/step - loss: 0.2509 - accuracy: 0.9175 - val_loss: 0.5738 - val_accuracy: 0.8260
Epoch 17/20
450/450 [==============================] - 0s 754us/step - loss: 0.2321 - accuracy: 0.9249 - val_loss: 0.5374 - val_accuracy: 0.8371
Epoch 18/20
450/450 [==============================] - 0s 761us/step - loss: 0.2179 - accuracy: 0.9313 - val_loss: 0.5503 - val_accuracy: 0.8405
Epoch 19/20
450/450 [==============================] - 0s 760us/step - loss: 0.2081 - accuracy: 0.9324 - val_loss: 0.5542 - val_accuracy: 0.8466
Epoch 20/20
450/450 [==============================] - 0s 754us/step - loss: 0.1931 - accuracy: 0.9378 - val_loss: 0.5761 - val_accuracy: 0.8338
57/57 [==============================] - 0s 462us/step - loss: 0.5761 - accuracy: 0.8338
Test Loss: 0.5761115550994873, Test Accuracy: 0.8337965607643127

In [119]:
model.save('model.h5')

/Users/nischalkashyap/.pyenv/versions/3.11.0/lib/python3.11/site-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [120]:
test

,length,chroma_stft_mean,chroma_stft_var,rms_mean,rms_var,spectral_centroid_mean,spectral_centroid_var,spectral_bandwidth_mean,spectral_bandwidth_var,rolloff_mean,...,mfcc16_var,mfcc17_mean,mfcc17_var,mfcc18_mean,mfcc18_var,mfcc19_mean,mfcc19_var,mfcc20_mean,mfcc20_var,id
0,66149,0.352453,0.079074,0.049762,0.000113,2182.571837,1.068958e+06,2793.933194,365598.217794,4882.736629,...,54.443741,-7.310032,54.092850,-3.083705,21.973936,-6.226634,47.559479,-10.531331,40.015507,9586
1,66149,0.478756,0.087817,0.161004,0.006013,2377.436870,4.982766e+05,2238.413578,145786.540526,4952.139799,...,68.952118,-5.488387,47.951576,4.220189,54.550598,-1.984476,83.323364,1.572527,59.916058,6984
2,66149,0.329632,0.076669,0.191606,0.000796,2525.119913,1.121766e+05,2472.943874,152231.535952,5245.819561,...,34.014881,-2.187970,48.011997,-5.302452,20.189150,-1.775238,33.344528,-1.861419,39.216839,7047
3,66149,0.302360,0.092979,0.106443,0.001762,1609.587478,1.552065e+05,2010.500266,66792.319500,3505.274189,...,61.442478,-7.453752,63.574467,6.466436,26.298433,-4.502402,47.922512,-4.084498,32.702728,2510
4,66149,0.400731,0.090858,0.125889,0.006567,1235.357695,2.267020e+05,1739.174077,218522.407816,2733.308857,...,48.944210,-2.122545,53.329845,-2.181120,41.637207,-3.361829,46.104019,-2.228968,30.943306,34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,66149,0.505255,0.074717,0.163630,0.002874,2400.403484,1.214451e+06,2504.768745,435455.640703,5095.915340,...,29.514904,-1.596965,31.212914,-3.638656,47.814972,-3.374476,35.619240,-2.141776,35.706924,4583
995,66149,0.441788,0.075458,0.126057,0.000848,2404.319614,1.693728e+05,2143.263729,76004.150528,4809.109638,...,30.936512,-8.983166,30.758400,4.631423,41.145515,-0.982899,33.679554,-3.411500,34.778164,6045
996,66149,0.209669,0.092197,0.045615,0.000233,2513.444580,1.737489e+04,1817.437810,12717.031917,4316.744666,...,26.008801,15.927879,27.391308,17.862923,38.844635,-11.587505,91.164101,-9.533628,79.951431,1897
997,66149,0.393056,0.079578,0.077266,0.000418,1965.229089,1.048652e+05,2072.314035,62326.933871,4110.771297,...,18.690699,-9.599170,22.972540,6.243433,28.810957,-7.491454,27.324255,0.586015,32.044926,3565
998,66149,0.201501,0.091407,0.114103,0.001621,2080.512374,2.021164e+05,2406.467386,119880.292389,4050.395508,...,38.185043,1.271115,38.480724,3.573726,96.871506,5.807116,146.409180,-4.746801,97.877602,5685

In [121]:
id = test['id']

In [122]:
test

,length,chroma_stft_mean,chroma_stft_var,rms_mean,rms_var,spectral_centroid_mean,spectral_centroid_var,spectral_bandwidth_mean,spectral_bandwidth_var,rolloff_mean,...,mfcc16_var,mfcc17_mean,mfcc17_var,mfcc18_mean,mfcc18_var,mfcc19_mean,mfcc19_var,mfcc20_mean,mfcc20_var,id
0,66149,0.352453,0.079074,0.049762,0.000113,2182.571837,1.068958e+06,2793.933194,365598.217794,4882.736629,...,54.443741,-7.310032,54.092850,-3.083705,21.973936,-6.226634,47.559479,-10.531331,40.015507,9586
1,66149,0.478756,0.087817,0.161004,0.006013,2377.436870,4.982766e+05,2238.413578,145786.540526,4952.139799,...,68.952118,-5.488387,47.951576,4.220189,54.550598,-1.984476,83.323364,1.572527,59.916058,6984
2,66149,0.329632,0.076669,0.191606,0.000796,2525.119913,1.121766e+05,2472.943874,152231.535952,5245.819561,...,34.014881,-2.187970,48.011997,-5.302452,20.189150,-1.775238,33.344528,-1.861419,39.216839,7047
3,66149,0.302360,0.092979,0.106443,0.001762,1609.587478,1.552065e+05,2010.500266,66792.319500,3505.274189,...,61.442478,-7.453752,63.574467,6.466436,26.298433,-4.502402,47.922512,-4.084498,32.702728,2510
4,66149,0.400731,0.090858,0.125889,0.006567,1235.357695,2.267020e+05,1739.174077,218522.407816,2733.308857,...,48.944210,-2.122545,53.329845,-2.181120,41.637207,-3.361829,46.104019,-2.228968,30.943306,34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,66149,0.505255,0.074717,0.163630,0.002874,2400.403484,1.214451e+06,2504.768745,435455.640703,5095.915340,...,29.514904,-1.596965,31.212914,-3.638656,47.814972,-3.374476,35.619240,-2.141776,35.706924,4583
995,66149,0.441788,0.075458,0.126057,0.000848,2404.319614,1.693728e+05,2143.263729,76004.150528,4809.109638,...,30.936512,-8.983166,30.758400,4.631423,41.145515,-0.982899,33.679554,-3.411500,34.778164,6045
996,66149,0.209669,0.092197,0.045615,0.000233,2513.444580,1.737489e+04,1817.437810,12717.031917,4316.744666,...,26.008801,15.927879,27.391308,17.862923,38.844635,-11.587505,91.164101,-9.533628,79.951431,1897
997,66149,0.393056,0.079578,0.077266,0.000418,1965.229089,1.048652e+05,2072.314035,62326.933871,4110.771297,...,18.690699,-9.599170,22.972540,6.243433,28.810957,-7.491454,27.324255,0.586015,32.044926,3565
998,66149,0.201501,0.091407,0.114103,0.001621,2080.512374,2.021164e+05,2406.467386,119880.292389,4050.395508,...,38.185043,1.271115,38.480724,3.573726,96.871506,5.807116,146.409180,-4.746801,97.877602,5685

In [123]:
test = test.drop(columns=['id'])

In [124]:
model = keras.models.load_model('model.h5')

# Standardise test data
scaler = StandardScaler()
test = scaler.fit_transform(test)
predictions = model.predict(test)

32/32 [==============================] - 0s 968us/step

In [125]:
label_binarizer = LabelBinarizer()

label_binarizer.fit(train['label'])
predicted_labels = label_binarizer.inverse_transform(predictions)

## **Map the encoded values to categories of music**

In [126]:
predict_mapped = [0 if val == 'blues' else
1 if val == 'classical' else
2 if val == 'country' else
3 if val == 'disco' else
4 if val == 'hiphop' else
5 if val == 'jazz' else
6 if val == 'metal' else
7 if val == 'pop' else
8 if val == 'reggae' else
9 for val in predicted_labels]
print(predict_mapped)

[9, 4, 7, 2, 0, 2, 6, 4, 3, 0, 3, 7, 6, 0, 9, 6, 7, 9, 5, 8, 3, 1, 3, 2, 4, 2, 4, 8, 8, 8, 1, 8, 5, 1, 3, 5, 3, 1, 0, 2, 8, 4, 5, 9, 7, 5, 3, 1, 0, 9, 8, 8, 0, 8, 1, 5, 1, 0, 1, 4, 6, 2, 0, 5, 2, 5, 8, 9, 4, 8, 2, 8, 4, 8, 0, 0, 3, 7, 1, 3, 0, 7, 7, 0, 3, 8, 4, 4, 2, 0, 2, 2, 3, 9, 4, 3, 9, 0, 0, 4, 5, 8, 3, 6, 5, 0, 0, 6, 6, 5, 3, 7, 1, 6, 9, 3, 2, 1, 6, 6, 3, 4, 5, 0, 0, 3, 6, 6, 3, 9, 7, 9, 2, 9, 6, 2, 3, 5, 6, 1, 4, 9, 2, 4, 3, 3, 5, 1, 8, 3, 9, 0, 2, 0, 9, 2, 5, 3, 1, 0, 9, 9, 3, 7, 3, 2, 5, 6, 1, 2, 8, 2, 3, 2, 5, 3, 0, 2, 1, 1, 5, 3, 6, 2, 1, 7, 5, 9, 0, 1, 1, 3, 4, 6, 7, 3, 9, 5, 8, 1, 2, 4, 7, 0, 5, 6, 9, 4, 5, 0, 5, 4, 5, 9, 7, 3, 2, 0, 4, 8, 9, 4, 5, 9, 7, 3, 2, 6, 3, 2, 7, 0, 0, 0, 4, 7, 5, 8, 1, 0, 4, 9, 5, 0, 3, 8, 7, 4, 4, 0, 0, 8, 9, 7, 3, 1, 0, 2, 1, 4, 0, 5, 0, 4, 8, 7, 9, 1, 5, 9, 9, 3, 7, 2, 9, 8, 3, 9, 3, 3, 0, 6, 8, 2, 2, 7, 4, 7, 2, 4, 6, 7, 6, 2, 5, 9, 4, 1, 5, 4, 7, 5, 4, 1, 6, 1, 6, 8, 1, 0, 7, 4, 5, 6, 6, 5, 8, 4, 9, 3, 5, 8, 3, 0, 3, 7, 5, 5, 6, 5, 5, 8, 3, 5, 3, 8, 6, 8, 2, 4, 3, 9, 0, 7, 6, 4, 5, 8, 9, 6, 2, 8, 7, 1, 9, 7, 3, 5, 7, 4, 2, 5, 1, 5, 9, 1, 8, 3, 7, 2, 0, 0, 3, 2, 3, 1, 3, 8, 0, 8, 1, 2, 1, 3, 3, 1, 7, 0, 6, 2, 6, 4, 9, 0, 6, 6, 8, 2, 3, 3, 5, 6, 6, 2, 2, 5, 5, 3, 5, 7, 7, 6, 7, 2, 5, 9, 4, 1, 5, 5, 1, 8, 4, 0, 6, 5, 3, 4, 1, 4, 5, 2, 3, 2, 6, 9, 6, 6, 7, 2, 4, 0, 3, 3, 1, 4, 3, 6, 1, 3, 6, 8, 6, 0, 9, 6, 4, 3, 4, 3, 6, 9, 5, 4, 8, 5, 6, 8, 7, 5, 7, 0, 1, 4, 0, 3, 2, 5, 9, 8, 5, 8, 8, 5, 0, 8, 5, 0, 1, 5, 7, 9, 8, 7, 0, 6, 1, 1, 9, 0, 4, 1, 0, 6, 9, 8, 0, 3, 3, 8, 8, 5, 3, 8, 3, 0, 6, 5, 3, 9, 0, 6, 8, 6, 9, 3, 0, 5, 5, 1, 6, 1, 5, 2, 0, 6, 1, 2, 7, 8, 8, 9, 0, 7, 6, 5, 6, 4, 6, 7, 3, 9, 4, 2, 9, 5, 3, 0, 8, 1, 1, 0, 5, 4, 5, 1, 4, 7, 2, 1, 6, 0, 4, 8, 2, 8, 7, 5, 6, 0, 9, 2, 3, 2, 4, 5, 0, 6, 3, 1, 2, 7, 3, 3, 6, 0, 2, 7, 4, 5, 9, 3, 0, 6, 4, 0, 1, 4, 4, 7, 5, 7, 3, 0, 8, 7, 9, 3, 9, 0, 4, 7, 4, 3, 1, 3, 3, 5, 8, 5, 2, 0, 1, 7, 4, 7, 1, 8, 4, 4, 7, 3, 8, 3, 3, 0, 2, 0, 0, 1, 0, 2, 2, 0, 1, 2, 2, 2, 9, 9, 9, 2, 1, 5, 4, 0, 3, 0, 5, 7, 0, 5, 4, 9, 3, 6, 3, 6, 7, 0, 3, 4, 5, 7, 6, 4, 5, 0, 2, 7, 5, 7, 7, 7, 4, 8, 2, 6, 8, 8, 0, 5, 2, 1, 5, 8, 2, 8, 6, 9, 7, 7, 8, 1, 1, 7, 1, 5, 5, 6, 2, 2, 8, 8, 5, 8, 2, 9, 0, 6, 1, 4, 0, 2, 4, 6, 9, 0, 5, 3, 6, 5, 2, 0, 9, 0, 6, 1, 6, 1, 0, 7, 5, 5, 5, 4, 2, 1, 6, 6, 7, 2, 6, 4, 2, 4, 4, 6, 1, 7, 0, 8, 7, 4, 6, 2, 6, 6, 6, 5, 1, 9, 2, 1, 4, 7, 7, 7, 7, 3, 4, 7, 1, 6, 6, 3, 7, 7, 0, 9, 8, 2, 4, 2, 7, 5, 6, 0, 7, 4, 5, 3, 1, 8, 6, 5, 6, 0, 4, 6, 4, 8, 9, 2, 2, 6, 0, 3, 4, 7, 0, 8, 9, 7, 7, 6, 5, 6, 3, 1, 2, 0, 2, 7, 2, 2, 4, 7, 0, 4, 1, 4, 2, 4, 6, 1, 3, 0, 5, 9, 8, 0, 5, 2, 8, 2, 3, 0, 0, 3, 4, 4, 2, 7, 6, 2, 8, 3, 5, 5, 4, 1, 1, 9, 7, 1, 3, 8, 4, 5, 4, 4, 4, 4, 4, 9, 1, 4, 0, 7, 8, 3, 8, 9, 0, 2, 0, 6, 4, 3, 1, 7, 2, 9, 5, 1, 2, 1, 2, 4, 8, 5, 5, 4, 7, 8, 9, 1, 1, 7, 3, 7, 0, 3, 6, 5, 0, 0, 8, 5, 4, 8, 1, 0, 8, 5, 9, 6, 7, 4, 7, 1, 3, 6, 3, 3, 8, 5, 8, 0, 1, 8, 3, 4, 0, 5, 3, 0, 2, 5, 3, 9, 2, 0, 7, 6, 1, 2, 8, 4, 9, 1, 5, 6, 8, 8, 1, 3, 0, 1, 4, 7, 4, 1, 4, 6, 1, 3, 5]

In [127]:
submission_df = pd.DataFrame({'id': id, 'label': predict_mapped})

In [128]:
submission_df

       id  label
0    9586      9
1    6984      4
2    7047      7
3    2510      2
4      34      0
..    ...    ...
994  4583      4
995  6045      6
996  1897      1
997  3565      3
998  5685      5

[999 rows x 2 columns]

In [129]:
submission_df.to_csv('submission.csv', index=False)